# Generated by Django 4.0.4 on 2022-05-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_user',
            new_name='owner',
        ),
    ]
